// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaJ-qWD2fS4-TtzYXxtk7DjJvAorIyQJo',
    appId: '1:18409244577:android:bca5b570fc78bdaf306de0',
    messagingSenderId: '18409244577',
    projectId: 'myelc-d7498',
    storageBucket: 'myelc-d7498.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlUL3dFHh7VwocD6mCKwo3RYn5PxsD2gY',
    appId: '1:18409244577:ios:0e1dfc453b8e96e8306de0',
    messagingSenderId: '18409244577',
    projectId: 'myelc-d7498',
    storageBucket: 'myelc-d7498.appspot.com',
    iosBundleId: 'com.example.myElc',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ6EhXWwfVo-PopQuiqfc40FUbFd5Qjck',
    appId: '1:18409244577:web:7367e2acb84706b4306de0',
    messagingSenderId: '18409244577',
    projectId: 'myelc-d7498',
    authDomain: 'myelc-d7498.firebaseapp.com',
    storageBucket: 'myelc-d7498.appspot.com',
    measurementId: 'G-KNKME8K0J6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlUL3dFHh7VwocD6mCKwo3RYn5PxsD2gY',
    appId: '1:18409244577:ios:0e1dfc453b8e96e8306de0',
    messagingSenderId: '18409244577',
    projectId: 'myelc-d7498',
    storageBucket: 'myelc-d7498.appspot.com',
    iosBundleId: 'com.example.myElc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ6EhXWwfVo-PopQuiqfc40FUbFd5Qjck',
    appId: '1:18409244577:web:1dba1720f26c1b31306de0',
    messagingSenderId: '18409244577',
    projectId: 'myelc-d7498',
    authDomain: 'myelc-d7498.firebaseapp.com',
    storageBucket: 'myelc-d7498.appspot.com',
    measurementId: 'G-HSZ50LV6Z0',
  );

}